version: '3.3'
services:
  web:
    build: ./web
    security_opt:
      - seccomp:unconfined
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net
    env_file:
      - .env

  scheduler:
    build: ./scheduler
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      RABBITMQ_HOST: "rabbitmq"

  worker:
    build: ./worker
    security_opt:
      - seccomp:unconfined
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      RABBITMQ_HOST: "rabbitmq"

volumes:
  mongo-data:

networks:
  app-net:
